#!/bin/bash

: "${XDG_CONFIG_HOME:=$HOME/.config}"
: "${ZDOTDIR:=$HOME}"

# Disallow ctrl+c after script start as it may break things
trap "" SIGINT

# Create home if doesn't exists
mkdir -p $XDG_CONFIG_HOME

# Create a backup directory
backup_dir="backup-$(date +%s)"
mkdir -p "$HOME/$backup_dir"

# setup wksp directory for projects
if [ ! -d "$HOME/wksp" ]; then
     mkdir $HOME/wksp
fi

clone() {
     echo "cloning into wksp directory"
     echo "cloning dots"
     git clone https://github.com/a-clean-kitchen/.dots.git $HOME/wksp/dots
     
     echo "cloning scripts"
     git clone https://github.com/a-clean-kitchen/scripts.git $HOME/wksp/scripts
}

backup() {
     cd $HOME/wksp/dots/.config
     echo "Backing up files to $HOME/$backup_dir/"
     for file in *; do
          if [ -d "$XDG_CONFIG_HOME/$file" ]; then
               mv "$XDG_CONFIG_HOME/$file" "$HOME/$backup_dir"
          fi
     done

     cd $HOME/wksp/dots/zsh
     mkdir -p "$HOME/$backup_dir/zsh/"
     echo "Backing up zsh config to $HOME/$backup_dir/zsh/"
     for file in .z*; do
          if [ -d "$ZDOTDIR/$file" ]; then
               mv "$ZDOTDIR/$file" "$HOME/$backup_dir/zsh/" 2>/dev/null
          fi
     done
}

symlink() {
     cd $HOME/wksp/dots
     echo "Symlinking files to $XDG_CONFIG_HOME"
     . symlink
     cd ..
     mkdir -p $HOME/.local 2>&1
     ln -sfn scripts/ $HOME/.local/scripts
     echo "All files linked successfully! :)"
}

clone
backup
symlink
