#!/bin/sh

## Add this to your wm startup file.

# Terminate already running bar instances
killall -q waybar

# Wait until the processes have been shut down
while pgrep -u $UID -x waybar >/dev/null; do sleep 1; done

waybar -l debug -c ~/.config/waybar/config -s ~/.config/waybar/style.css  2>/dev/null &
